const AppConfig = {

    apiToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhaHVsa3VtYXIxMjNAZ21haWwuY29tIiwidXNlcklkIjoiNjE1MWYyNDVlOTI4ZTQwMDE1MWJjYWE5IiwiaWF0IjoxNjMzMjgwNDgxLCJleHAiOjE2MzMzNjY4ODF9.xOQOVQZrvK3X6SwGj78SUuivI8wbV4nQ83HO1dq2-Rg"
}
export default AppConfig;