const AppConfig = {

    apiToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhaHVsa3VtYXIxMjNAZ21haWwuY29tIiwidXNlcklkIjoiNjE1MWYyNDVlOTI4ZTQwMDE1MWJjYWE5IiwiaWF0IjoxNjMzODc5OTMyLCJleHAiOjE2MzM5NjYzMzJ9.uZy1jbHaH1NGsuwwwjK7xPZ6wC3FNcDI2Kjr5S5NarI"
}
export default AppConfig;